#!/usr/bin/env python
"""

This is really stupid and simple parsing/generation, since there aren't that many C bindings

Usage: python nncbindgen.py <path within include/nn>

Put // @nncbindgen above the struct/enum/function to generate the binding for.
For typedefs put // @nncbindgen typedef <inner_type>

Putting // @nncbindgen skip above an include skips that include in the C version

Generated structs are opaque. To actually access the fields you need
to implement the type manually instead of generating one.

"""

from pathlib import Path
import tempfile
import subprocess
import os
import sys

INCLUDE_MAP = {
    "<cstdint>": None,
    "<nn/util.h>": None # TODO: these macros need to be available to nnc but there are some cpp only stuff
}
ALIGN_HOLDER = {
    1: "char", # for placeholder types
    8: "void*"
}
TYPE_MAP = {}

def main(file: str, check: bool):
    include_root = get_include_root();
    input_file = include_root / "nn" / file
    output_file = include_root / "nnc" / file

    if check and not output_file.exists():
        raise RuntimeError(f"nnc binding for {file} needs to be generated; please run task cbindgen")

    output_lines = process(file, input_file.read_text())

    output_parent = output_file.parent
    output_parent.mkdir(parents=True, exist_ok=True)

    current_file = output_file.read_text() if output_file.exists() else ""
    current_lines = [ x.rstrip() for x in current_file.strip().split("\n") ]

    if current_lines == output_lines and current_file.endswith("\n"):
        if check:
            print(f"up-to-date: nnc/{file}")
        return

    if check:
        raise RuntimeError(f"nnc binding for {file} needs to be updated; please run task cbindgen")

    output_file.write_text("\n".join(x.rstrip() for x in output_lines) + "\n")
    print(f"updated: nnc/{file}")




def process(input_file_ident: str, input_file: str):
    output: list[str] = [
        "// clang-format off",
        "// NOLINTBEGIN",
        f"// GENERATED BY NNCBINDGEN from {input_file_ident}",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
    ]
    last_item_type = None
    is_extern_c = False
    def extern_c_start():
        nonlocal output
        nonlocal is_extern_c
        nonlocal last_item_type
        if is_extern_c: return
        output += [
            "",
            "#ifdef __cplusplus",
            "extern \"C\" {",
            "#endif",
        ]
        last_item_type = None
        is_extern_c = True
    def extern_c_end():
        nonlocal output
        nonlocal is_extern_c
        nonlocal last_item_type
        if not is_extern_c: return
        output += [
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif"
            "",
        ]
        last_item_type = None
        is_extern_c = False
    def enter_item_region(t: str):
        nonlocal last_item_type
        if last_item_type != t:
            output.append("")
            last_item_type = t

    directive_stack: list[dict] = [{
        "type": "none"
    }]
    is_bulk_skipping = False
    namespace = ""
    node_buffer_stack = []

    for line in input_file.split('\n'):
        line = line.strip()
        if not line.startswith("//"):
            i = line.find("//")
            if i > 0:
                line = line[:i].strip()
        if not line:
            continue
        if line.startswith("#include "):
            if directive_stack[-1]["type"] == "skip":
                if not is_bulk_skipping:
                    directive_stack.pop()
                    node_buffer_stack.pop()
                continue

            include = line[len("#include "):].strip()
            if include in INCLUDE_MAP:
                include = INCLUDE_MAP[include]
                if include:
                    enter_item_region("system-include")
                    output.append(f"#include {include}")
            elif include.startswith("<nn/"):
                include = "<nnc/" + include[4:]
                enter_item_region("nn-include")
                output.append(f"#include {include}")
            else:
                enter_item_region("other-include")
                output.append(f"#include {include}")
            continue

        if line.startswith("namespace "):
            ns = line[len("namespace "):-1].strip()
            namespace = ns
            continue

        if line.startswith("// @nncbindgen"):
            d = line[len("// @nncbindgen"):].strip()
            attrs, d = parse_directive_attrs(d)
            args = d.split(" ")[1:]
            if not d:
                directive_stack.append({ "type": "auto", "attrs": attrs })
            elif d.startswith("typedef"):
                typedef_t = d[len("typedef"):].strip()
                if not typedef_t:
                    raise RuntimeError("missing type after typedef directive")
                directive_stack.append({ "type": "typedef", "target": typedef_t })
            elif d.startswith("skip-start"):
                directive_stack.append({ "type": "skip" })
                is_bulk_skipping = True
            elif d.startswith("skip-end"):
                directive_stack.pop()
                node_buffer_stack.pop()
                is_bulk_skipping = False
            elif d.startswith("define"):
                TYPE_MAP[args[1]]=args[0]
            elif d.startswith("skip"):
                directive_stack.append({ "type": "skip" })
            else:
                raise RuntimeError("unknown directive: " + d)
            node_buffer_stack.append("")
            continue

        if directive_stack[-1]["type"] == "none" or not node_buffer_stack:
            continue

        i = line.find("//")
        if i > 0:
            line = line[:i].strip()

        node_buffer_stack[-1] += line
        # note this doesn't get the full class but that's fine for now
        # as we only need the class name, the important thing is it gets
        # all lines for a function
        if line.endswith(";"):
            directive = directive_stack[-1]
            rename = None
            containing_class = None
            current_namespace = namespace
            if "attrs" in directive:
                rename = directive["attrs"].get("rename")
                containing_class = directive["attrs"].get("memberof")
                override_namespace = directive["attrs"].get("namespace")
                if override_namespace:
                    current_namespace = override_namespace

            out_type, lines = process_node(
                input_file_ident,
                directive,
                current_namespace,
                node_buffer_stack[-1],
                rename,
                containing_class
            )
            node_buffer_stack.pop()
            directive_stack.pop()
            extern_c_start()
            enter_item_region(out_type)
            output += lines

    extern_c_end()
    output += [
        "",
        "// NOLINTEND",
        "// clang-format off"
    ]

    return output


def parse_directive_attrs(directive: str) -> tuple[dict, str]:
    directive = directive.strip()
    if not directive.startswith("("):
        return {}, directive
    i = directive.find(")")
    attrs = directive[1:i].strip().split(",")
    directive = directive[i+1:].strip()
    parsed_attrs = {}
    for attr in attrs:
        i = attr.find("=")
        attr_name = attr[:i].strip()
        attr_value = attr[i+1:].strip()
        parsed_attrs[attr_name] = attr_value
    return parsed_attrs, directive

def process_node(
    input_file: str,
    directive,
    namespace: str,
    node_buffer: str,
    rename: str | None,
    containing_class: str | None
):
    out_type = ""
    out = []
    c_namespace = namespace.replace("::", "").strip()
    symbol_c_namespace = c_namespace
    cpp_namespace = namespace
    if containing_class:
        symbol_c_namespace += containing_class
        cpp_namespace += "::" + containing_class
    if node_buffer.startswith("struct ") or node_buffer.startswith("class "):
        i = node_buffer.find("{")
        struct_name = node_buffer[6:i].strip()
        if rename:
            struct_name = rename
        out_type = f"struct {struct_name}"
        if directive["type"] == "typedef":
            out = [
                f"typedef {directive["target"]} {symbol_c_namespace}{struct_name};"
            ]
        else:
            size, align = figure_out_size_and_align(input_file, f"{cpp_namespace}::{struct_name}")
            if align not in ALIGN_HOLDER:
                raise RuntimeError(f"alignment {align} is currently not implemented")
            align_type = ALIGN_HOLDER[align]
            out = [
                f"typedef union {symbol_c_namespace}{struct_name} {{ uint8_t buf[{size:#x}]; {align_type} alignment_holder; }} {symbol_c_namespace}{struct_name};"
            ]
        return out_type, out

    if node_buffer.startswith("enum "):
        i = node_buffer.find("{")
        enum_name = node_buffer[len("enum"):i].strip()
        enumerators_prefix = symbol_c_namespace
        if enum_name.startswith("class "):
            enum_name = enum_name[len("class"):].strip()
            enumerators_prefix += enum_name + "_"
        j = node_buffer.rfind("}")
        enumerators = []
        for e in node_buffer[i+1:j].split(","):
            e = e.strip();
            if not e:
                continue
            enumerators.append("    " + enumerators_prefix + e + ",")
        out = [
            f"typedef enum {symbol_c_namespace}{enum_name} {{",
            *enumerators,
            f"}} {symbol_c_namespace}{enum_name};",
        ]
        return f"enum {enum_name}", out

    return "function", [ parse_function(c_namespace, node_buffer, rename, containing_class, symbol_c_namespace) ]


def figure_out_size_and_align(input_file: str, typename: str):
    # can't run the output since it's for the switch, so compile the values
    # into a data constant and read them back from the generated assembly
    symbol = "nncbindgen_size_align"
    temp_cpp_file = "\n".join([
        f"#include <nn/{input_file}>",
        f"extern \"C\" __attribute__((used)) const unsigned long long {symbol}[2] = {{",
        f"    sizeof({typename}), alignof({typename})",
        "};",
    ])
    with tempfile.NamedTemporaryFile(mode="w+", delete=True, suffix=".cpp") as input_cpp:
        input_cpp.write(temp_cpp_file)
        input_cpp.flush()
        include_path = str(get_include_root())
        if " " in include_path:
            raise RuntimeError("project path cannot contain spaces")
        asm = subprocess.check_output([
            str(get_nx_clang() / "bin" / "clang++"),
            "--target=aarch64-linux-elf",
            "-mcpu=cortex-a57+fp+simd+crypto+crc",
            "-std=c++17",
            "-stdlib=libc++",
            f"--sysroot={str(get_musl())}",
            f"-I{include_path}",
            "-DSWITCH",
            "-DNNSDK",
            "-DMATCHING_HACK_NX_CLANG",
            "-S",
            "-o",
            "-",
            input_cpp.name,
        ], text=True)

    lines = [ x.strip() for x in asm.split("\n") ]
    try:
        i = lines.index(f"{symbol}:")
    except ValueError:
        raise RuntimeError(f"cannot find {symbol} in compiled assembly:\n{asm}")
    values = []
    for line in lines[i+1:i+3]:
        parts = line.split()
        if len(parts) < 2 or parts[0] != ".xword":
            raise RuntimeError(f"unexpected assembly for {symbol}: {line}")
        values.append(int(parts[1], 0))
    size, align = values
    return size, align

def parse_function(
    c_namespace: str,
    node_buffer: str,
    rename: str | None,
    containing_class: str | None,
    symbol_c_namespace: str,
) -> str:
    if "<" in node_buffer or ">" in node_buffer:
        raise RuntimeError("looks like there are type parameters so this can't be parse as a c function: " + node_buffer)
    if "&" in node_buffer:
        raise RuntimeError("looks like there are reference types so this can't be parse as a c function: " + node_buffer)
    i = node_buffer.find("(")
    retty_and_name = node_buffer[:i].strip()
    parts = retty_and_name.split(" ")
    if len(parts) != 2:
        raise RuntimeError("there are too many spaces in the return type and function name")
    retty, name = parts
    if rename:
        name = rename
    j = node_buffer.rfind(")")
    middle = node_buffer[i+1:j].strip().split(",")
    args = []
    if containing_class:
        args.append(convert_to_c_type(c_namespace, f"{containing_class}* this_"))
    for arg_type_and_name in middle:
        converted = convert_to_c_type(c_namespace, arg_type_and_name)
        if not converted:
            continue
        args.append(converted)
    c_retty = convert_to_c_type(c_namespace, retty)
    return f"{c_retty} {symbol_c_namespace}{name}({", ".join(args)});"

def convert_to_c_type(c_namespace: str, t: str) -> str:
    namespace_segs = t.strip().split("::")
    # if a fully qualified nn type, concat it already
    if namespace_segs and namespace_segs[0].strip() == "nn":
        namespace_segs = [t.strip().replace("::", "")]
    converted_segs = []
    for seg in namespace_segs:
        parts = seg.split(" ")
        converted_parts = []
        for p in parts:
            c_type = ""
            if p in TYPE_MAP:
                c_type = TYPE_MAP[p]+" "
            if p and p[0].isupper():
                converted_parts.append(c_type + c_namespace + p)
            else:
                converted_parts.append(c_type + p)
        converted_segs.append(" ".join(converted_parts))
    output = "".join(converted_segs)
    return output

def get_nx_clang():
    clang = os.environ.get("NX_CLANG")
    if clang:
        return Path(clang)
    aarch64 = os.environ.get("NX_AARCH64")
    if not aarch64:
        raise RuntimeError("either NX_CLANG or NX_AARCH64 must be set")
    clang = get_toolchain_root() / f"nx-aarch64-{aarch64}"
    if not clang.is_dir():
        raise RuntimeError("cannot find nx-aarch64")
    return Path(clang)
    

def get_musl():
    musl = os.environ.get("NX_MUSL")
    if musl:
        return Path(musl)
    musl = get_toolchain_root() / "musl"
    if not musl.is_dir():
        raise RuntimeError("cannot find musl")
    return Path(musl)

def get_toolchain_root():
    return Path(__file__).resolve().parent / "toolchain"

def get_include_root():
    return Path(__file__).resolve().parent / "include"

if __name__ == "__main__":
    if not os.environ.get("NX_CLANG") and not os.environ.get("NX_AARCH64"):
        print("please run this script through task - run 'task cbindgen'")
        exit(1)

    try:
        get_nx_clang()
    except:
        print("cannot find nx-aarch64, please run 'task configure' to download it")
    try:
        get_musl()
    except:
        print("cannot find musl, please run 'task configure' to download it")

    check = bool(os.environ.get("NN_CBINDGEN_CHECK")) or bool(os.environ.get("CI"))
    file = sys.argv[1]
    try:
        main(file, check)
    except:
        print("failed to generate nnc bindings for: " + file)
        raise
