#!/usr/bin/env python
"""

This is really stupid and simple parsing/generation, since there aren't that many C bindings

Usage: python nncbindgen.py <path within include/nn>

Put // @nncbindgen above the struct/enum/function to generate the binding for.
For typedefs put // @nncbindgen typedef <inner_type>

Putting // @nncbindgen skip above an include skips that include in the C version

Generated structs are opaque. To actually access the fields you need
to implement the type manually instead of generating one.

"""

from pathlib import Path
import tempfile
import subprocess
import os
import sys

INCLUDE_MAP = {
    "<cstdint>": None,
    "<nn/util.h>": None # TODO: these macros need to be available to nnc but there are some cpp only stuff
}
ALIGN_HOLDER = {
    8: "void*"
}

def main(file: str, check: bool):
    include_root = get_include_root();
    input_file = include_root / "nn" / file
    output_file = include_root / "nnc" / file

    if check and not output_file.exists():
        raise RuntimeError(f"nnc binding for {file} needs to be generated; please run task cbindgen")

    output_lines = process(file, input_file.read_text())

    output_parent = output_file.parent
    output_parent.mkdir(parents=True, exist_ok=True)

    current_file = output_file.read_text() if output_file.exists() else ""
    current_lines = [ x.rstrip() for x in current_file.strip().split("\n") ]

    if current_lines == output_lines and current_file.endswith("\n"):
        print(f"up-to-date: nnc/{file}")
        return

    if check:
        raise RuntimeError(f"nnc binding for {file} needs to be updated; please run task cbindgen")

    output_file.write_text("\n".join(x.rstrip() for x in output_lines) + "\n")
    print(f"updated: nnc/{file}")




def process(input_file_ident: str, input_file: str):
    output: list[str] = [
        "// clang-format off",
        "// NOLINTBEGIN",
        f"// GENERATED BY NNCBINDGEN from {input_file_ident}",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
    ]
    last_item_type = None
    is_extern_c = False
    def extern_c_start():
        nonlocal output
        nonlocal is_extern_c
        nonlocal last_item_type
        if is_extern_c: return
        output += [
            "",
            "#ifdef __cplusplus",
            "extern \"C\" {",
            "#endif",
        ]
        last_item_type = None
        is_extern_c = True
    def extern_c_end():
        nonlocal output
        nonlocal is_extern_c
        nonlocal last_item_type
        if not is_extern_c: return
        output += [
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif"
            "",
        ]
        last_item_type = None
        is_extern_c = False
    def enter_item_region(t: str):
        nonlocal last_item_type
        if last_item_type != t:
            output.append("")
            last_item_type = t

    directive = {
        "type": "none"
    }
    namespace = ""
    node_buffer = ""

    for line in input_file.split('\n'):
        line = line.strip()
        if not line.startswith("//"):
            i = line.find("//")
            if i > 0:
                line = line[:i].strip()
        if not line:
            continue
        if line.startswith("#include "):
            if directive["type"] == "skip":
                directive = { "type": "none" }
                continue

            include = line[len("#include "):].strip()
            if include in INCLUDE_MAP:
                include = INCLUDE_MAP[include]
                if include:
                    enter_item_region("system-include")
                    output.append(f"#include {include}")
            elif include.startswith("<nn/"):
                include = "<nnc/" + include[4:]
                enter_item_region("nn-include")
                output.append(f"#include {include}")
            else:
                enter_item_region("other-include")
                output.append(f"#include {include}")
            continue

        if line.startswith("namespace "):
            ns = line[len("namespace "):-1].strip()
            namespace = ns
            continue

        if line.startswith("// @nncbindgen"):
            d = line[len("// @nncbindgen"):].strip()
            if not d:
                directive = { "type": "auto" }
            elif d.startswith("typedef"):
                typedef_t = d[len("typedef"):].strip()
                if not typedef_t:
                    raise RuntimeError("missing type after typedef directive")
                directive = { "type": "typedef", "target": typedef_t }
            elif d.startswith("skip"):
                directive = { "type": "skip" }
            else:
                raise RuntimeError("unknown directive: " + d)
            continue

        if directive["type"] == "none":
            continue

        i = line.find("//")
        if i > 0:
            line = line[:i].strip()

        node_buffer += line
        if line.endswith(";"):
            out_type, lines = process_node(input_file_ident, directive, namespace, node_buffer)
            node_buffer = ""
            directive = { "type": "none" }
            extern_c_start()
            enter_item_region(out_type)
            output += lines

    extern_c_end()
    output += [
        "",
        "// NOLINTEND",
        "// clang-format off"
    ]

    return output


def process_node(input_file: str, directive, namespace: str, node_buffer: str):
    out_type = ""
    out = []
    c_namespace = namespace.replace("::", "").strip()
    if node_buffer.startswith("struct "):
        i = node_buffer.find("{")
        struct_name = node_buffer[len("struct"):i].strip()
        out_type = f"struct {struct_name}"
        if directive["type"] == "typedef":
            out = [
                f"typedef {directive["target"]} {c_namespace}{struct_name};"
            ]
        else:
            size, align = figure_out_size_and_align(input_file, f"{namespace}::{struct_name}")
            if align not in ALIGN_HOLDER:
                raise RuntimeError(f"alignment {align} is currently not implemented")
            align_type = ALIGN_HOLDER[align]
            out = [
                f"union {c_namespace}{struct_name} {{ uint8_t buf[{size:#x}]; {align_type} alignment_holder; }};"
            ]
        return out_type, out

    if node_buffer.startswith("enum "):
        i = node_buffer.find("{")
        enum_name = node_buffer[len("enum"):i].strip()
        j = node_buffer.rfind("}")
        enumerators = ["    " + c_namespace + x.strip() + "," for x in node_buffer[i+1:j].split(",")]
        out = [
            f"enum {c_namespace}{enum_name} {{",
            *enumerators,
            "};",
        ]
        return f"enum {enum_name}", out

    return "function", [ parse_function(c_namespace, node_buffer) ]


def figure_out_size_and_align(input_file: str, typename: str):
    temp_cpp_file = "\n".join([
        "#include <cstdio>",
        f"#include <nn/{input_file}>",
        "int main() {",
        f"printf(\"%zu %zu\\n\", sizeof({typename}), alignof({typename}));",
        "return 0;",
        "}",
    ])
    with tempfile.NamedTemporaryFile(mode="w+", delete=True, suffix=".cpp") as input_cpp:
        input_cpp.write(temp_cpp_file)
        input_cpp.flush()
        with tempfile.NamedTemporaryFile(mode="w+", delete=False, suffix="") as output_bin:
            output_bin_name = output_bin.name
            include_path = str(get_include_root())
            if " " in include_path:
                raise RuntimeError("project path cannot contain spaces")
            subprocess.check_call([
                "clang",
                "-std=c++17",
                f"-I{str(get_include_root())}",
                input_cpp.name,
                "-o",
                output_bin.name
            ])
        output = subprocess.check_output([output_bin_name], text=True)
        os.remove(output_bin_name)

    size, align = output.split(" ")
    return int(size), int(align)

def parse_function(c_namespace: str, node_buffer: str) -> str:
    if "<" in node_buffer or ">" in node_buffer:
        raise RuntimeError("looks like there are type parameters so this can't be parse as a c function: " + node_buffer)
    if "&" in node_buffer:
        raise RuntimeError("looks like there are reference types so this can't be parse as a c function: " + node_buffer)
    i = node_buffer.find("(")
    retty_and_name = node_buffer[:i].strip()
    parts = retty_and_name.split(" ")
    if len(parts) != 2:
        raise RuntimeError("there are too many spaces in the return type and function name")
    retty, name = parts
    j = node_buffer.rfind(")")
    middle = node_buffer[i+1:j].strip().split(",")
    args = []
    for arg_type_and_name in middle:
        converted = convert_to_c_type(c_namespace, arg_type_and_name)
        args.append(converted)
    c_retty = convert_to_c_type(c_namespace, retty)
    return f"{c_retty} {c_namespace}{name}({", ".join(args)});"

def convert_to_c_type(c_namespace: str, t: str) -> str:
    namespace_segs = t.strip().split("::")
    converted_segs = []
    for seg in namespace_segs:
        parts = seg.split(" ")
        converted_parts = []
        for p in parts:
            if p and p[0].isupper():
                converted_parts.append(c_namespace + p)
            else:
                converted_parts.append(p)
        converted_segs.append(" ".join(converted_parts))
    output = "".join(converted_segs)
    return output



def get_include_root():
    return Path(__file__).resolve().parent / "include"

if __name__ == "__main__":
    check = bool(os.environ.get("NN_CBINDGEN_CHECK")) or bool(os.environ.get("CI"))
    main(sys.argv[1], check)
