#pragma once

namespace nn::am {
// based on https://switchbrew.org/wiki/Applet_Manager_services#AppletMessage
enum AppletMessage {
    AppletMessage_None = 0,
    AppletMessage_ChangeIntoForeground = 1,
    AppletMessage_ChangeIntoBackground = 2,
    AppletMessage_ExitRequested = 4,
    AppletMessage_ApplicationExited = 6,
    AppletMessage_7 = 7,
    AppletMessage_FocusStateChanged = 15,
    AppletMessage_Resume = 16,
    AppletMessage_DetectShortPressingHomeButton = 20,
    AppletMessage_DetectLongPressingHomeButton = 21,
    AppletMessage_DetectShortPressingPowerButton = 22,
    AppletMessage_DetectMiddlePressingPowerButton = 23,
    AppletMessage_DetectLongPressingPowerButton = 24,
    AppletMessage_RequestToPrepareSleep = 25,
    AppletMessage_FinishedSleepSequence = 26,
    AppletMessage_SleepRequiredByHighTemperature = 27,
    AppletMessage_SleepRequiredByLowBattery = 28,
    AppletMessage_AutoPowerDown = 29,
    AppletMessage_OperationModeChanged = 30,
    AppletMessage_PerformanceModeChanged = 31,
    AppletMessage_DetectReceivingCecSystemStandby = 32,
    AppletMessage_SdCardRemoved = 33,
    AppletMessage_34 = 34,
    AppletMessage_LaunchApplicationRequested = 50,
    AppletMessage_RequestToDisplay = 51,
    AppletMessage_ShowApplicationLogo = 55,
    AppletMessage_HideApplicationLogo = 56,
    AppletMessage_ForceHideApplicationLogo = 57,
    AppletMessage_58 = 58,
    AppletMessage_59 = 59,
    AppletMessage_FloatingApplicationDetected = 60,
    // 7.0.0+
    AppletMessage_PerformanceConfigurationChanged = 61,
    AppletMessage_70 = 70,
    AppletMessage_71 = 71,
    AppletMessage_72 = 72,
    AppletMessage_73 = 73,
    AppletMessage_75 = 75,
    AppletMessage_80 = 80,
    AppletMessage_81 = 81,
    AppletMessage_82 = 82,
    AppletMessage_83 = 83,
    AppletMessage_85 = 85,
    AppletMessage_86 = 86,
    AppletMessage_DetectShortPressingCaptureButton = 90,
    AppletMessage_AlbumScreenShotTaken = 92,
    AppletMessage_AlbumRecordingSaved = 93,
    AppletMessage_94 = 94,
    AppletMessage_100 = 100,
    AppletMessage_101 = 101,
    // 14.0.0+
    AppletMessage_DetectShortPressingCaptureButtonForApplet = 110,
    // 14.0.0+
    AppletMessage_DetectLongPressingCaptureButtonForApplet = 111,
    AppletMessage_1000 = 1000,
};
}  // namespace nn::am
