// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from os/os_EventCommon.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

enum nnosEventClearMode {
    nnosEventClearMode_ManualClear,
    nnosEventClearMode_AutoClear,
};

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
