// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from os/os_MutexTypes.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef union nnosMutexType { uint8_t buf[0x20]; void* alignment_holder; } nnosMutexType;

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
