// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from os/os_Mutex.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#include <nnc/os/os_MutexTypes.h>

#ifdef __cplusplus
extern "C" {
#endif

void nnosInitializeMutex(nnosMutexType*, bool recursive, int32_t lockLevel);
void nnosFinalizeMutex(nnosMutexType*);
void nnosLockMutex(nnosMutexType*);
bool nnosTryLockMutex(nnosMutexType*);
void nnosUnlockMutex(nnosMutexType*);

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
