// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from os/os_TickTypes.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint64_t nnosTick;

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
