name: pr
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        NN_VER:
          - version: 0.12.14 #BOTW 1.0.0
            target: aarch64
          - version: 0.12.16 #MK8DX 1.0.0
            target: arm
          - version: 3.5.1 #SMO 1.0.0
            target: aarch64
          - version: 4.4.0 #BOTW 1.5.0
            target: aarch64
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/open-ead/ubuntu-builder
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: false
      - run: task pr-build
        env:
          NN_VER: ${{matrix.NN_VER.version}}
          NN_TARGET: ${{matrix.NN_VER.target}}

  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/open-ead/ubuntu-builder
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: false
      - run: task pr-check

  check-nnware:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/open-ead/ubuntu-builder
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: false
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: false
          repository: open-ead/nnware
          path: lib/nnware
      - name: Build nnware
        working-directory: lib/nnware
        env:
          NNSDK_DIR: ${{ github.workspace }}
        run: |
          task configure
          task build
