// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from os.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#include <nnc/os/os_Mutex.h>
#include <nnc/os/os_MutexTypes.h>
#include <nnc/os/os_ThreadCommon.h>
#include <nnc/os/os_ThreadTypes.h>
#include <nnc/os/os_TickTypes.h>

#ifdef __cplusplus
extern "C" {
#endif

nnResult nnosCreateThread(nnosThreadType*, void (*)(void*), void* arg, void* srcStack, uint64_t stackSize, int32_t priority);
void nnosDestroyThread(nnosThreadType*);
void nnosStartThread(nnosThreadType*);
void nnosSleepThread(nnTimeSpan);
void nnosWaitThread(nnosThreadType*);

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
