// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from socket.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#include <netdb.h>

#include <nnc/nn_Result.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t nnsocketRecv(int32_t socket, void* out, size_t outLen, int32_t flags);
int32_t nnsocketSend(int32_t socket, const void* data, size_t dataLen, int32_t flags);
int32_t nnsocketBind(int, const struct sockaddr*, uint32_t);
nnResult nnsocketConnect(int32_t socket, const struct sockaddr* address, uint32_t addressLen);
int32_t nnsocketGetPeerName(int, struct sockaddr*, uint32_t*);
int32_t nnsocketGetSockName(int, struct sockaddr*, uint32_t*);
int32_t nnsocketGetSockOpt(int, int, int, void*, uint32_t*);
int32_t nnsocketSetSockOpt(int32_t socket, int32_t socketLevel, int32_t option, const void*, uint32_t len);
int32_t nnsocketSocket(int32_t domain, int32_t type, int32_t protocol);
nnResult nnsocketClose(int32_t socket);
int32_t nnsocketPoll(struct pollfd*, size_t, int);
int32_t nnsocketFcntl(int, int, ...);
uint16_t nnsocketInetHtons(uint16_t val);
uint32_t nnsocketInetHtonl(uint32_t);
uint16_t nnsocketInetNtohs(uint16_t);
uint32_t nnsocketInetNtohl(uint32_t);
int32_t nnsocketGetLastErrno();
void nnsocketSetLastErrno(int);
struct hostent* nnsocketGetHostByNameCancel(const char* name);
int32_t nnsocketRequestCancelHandle();
int32_t nnsocketCancel(int);

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
